ratings:
  namespace: student9-bookinfo-uat
  image: ghcr.io/kampol-nui/details-service
  tag: dev
  replicas: 1
  imagePullSecrets: registry-details
  port: 8080
  healthCheckPath: "/health"
ingress:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  host: bookinfo.uat.opsta.net
  path: "/student9/details(/|$)(.*)"
  serviceType: ClusterIP
# extraEnv:
#   SERVICE_VERSION: v2
#   MONGO_DB_URL: mongodb://bookinfo-dev-ratings-mongodb:27017/ratings